# SPDX-FileCopyrightText: 2024 Osnabrück University of Applied Sciences
# SPDX-FileContributor: Andreas Schliebitz
# SPDX-FileContributor: Henri Graf
# SPDX-FileContributor: Jonas Tüpker
# SPDX-FileContributor: Lukas Hesse
# SPDX-FileContributor: Maik Fruhner
# SPDX-FileContributor: Prof. Dr.-Ing. Heiko Tapken
# SPDX-FileContributor: Tobias Wamhof
#
# SPDX-License-Identifier: MIT

"""Adding unidirectional One-to-One relationship from TrainContainer to Dataset.

Revision ID: 63a39c8b5b92
Revises: f855b83d3f97
Create Date: 2022-07-13 08:30:20.649781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "63a39c8b5b92"
down_revision = "f855b83d3f97"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "train_containers", sa.Column("container_id", sa.String(), nullable=True)
    )
    op.drop_column("train_containers", "platform")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "train_containers",
        sa.Column("platform", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("train_containers", "container_id")
    # ### end Alembic commands ###
