# SPDX-FileCopyrightText: 2024 Osnabrück University of Applied Sciences
# SPDX-FileContributor: Andreas Schliebitz
# SPDX-FileContributor: Henri Graf
# SPDX-FileContributor: Jonas Tüpker
# SPDX-FileContributor: Lukas Hesse
# SPDX-FileContributor: Maik Fruhner
# SPDX-FileContributor: Prof. Dr.-Ing. Heiko Tapken
# SPDX-FileContributor: Tobias Wamhof
#
# SPDX-License-Identifier: MIT

"""adding metadata_uri to model

Revision ID: 745c4598e1f1
Revises: 5717a13f0471
Create Date: 2022-05-11 13:29:40.167976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "745c4598e1f1"
down_revision = "5717a13f0471"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("models", sa.Column("metadata_uri", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("models", "metadata_uri")
    # ### end Alembic commands ###
