# SPDX-FileCopyrightText: 2024 Osnabrück University of Applied Sciences
# SPDX-FileContributor: Andreas Schliebitz
# SPDX-FileContributor: Henri Graf
# SPDX-FileContributor: Jonas Tüpker
# SPDX-FileContributor: Lukas Hesse
# SPDX-FileContributor: Maik Fruhner
# SPDX-FileContributor: Prof. Dr.-Ing. Heiko Tapken
# SPDX-FileContributor: Tobias Wamhof
#
# SPDX-License-Identifier: MIT

"""Creation of Managment for Connectors

Revision ID: 9821b82c3c50
Revises: 5e922dceeaf1
Create Date: 2023-07-10 09:59:18.109429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9821b82c3c50"
down_revision = "5e922dceeaf1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connectors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("data_url", sa.String(), nullable=True),
        sa.Column("ids_url", sa.String(), nullable=True),
        sa.Column("minio_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_connectors_id"), "connectors", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_connectors_id"), table_name="connectors")
    op.drop_table("connectors")
    # ### end Alembic commands ###
