# SPDX-FileCopyrightText: 2024 University of Applied Sciences Osnabrück
# SPDX-FileContributor: Andreas Schliebitz
# SPDX-FileContributor: Henri Graf
# SPDX-FileContributor: Jonas Tüpker
# SPDX-FileContributor: Lukas Hesse
# SPDX-FileContributor: Maik Fruhner
# SPDX-FileContributor: Prof. Dr.-Ing. Heiko Tapken
# SPDX-FileContributor: Tobias Wamhof
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""changing inference to inferences

Revision ID: 9cffb0aa1272
Revises: 75e85a8e808c
Create Date: 2024-11-27 11:20:18.862870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9cffb0aa1272"
down_revision = "75e85a8e808c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_inference_id", table_name="inference")
    op.drop_table("inference")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inference",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("owner", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "last_modified", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("bucket_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("metadata_uri", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="inference_pkey"),
    )
    op.create_index("ix_inference_id", "inference", ["id"], unique=False)
    # ### end Alembic commands ###
