# SPDX-FileCopyrightText: 2024 University of Applied Sciences Osnabrück
# SPDX-FileContributor: Andreas Schliebitz
# SPDX-FileContributor: Henri Graf
# SPDX-FileContributor: Jonas Tüpker
# SPDX-FileContributor: Lukas Hesse
# SPDX-FileContributor: Maik Fruhner
# SPDX-FileContributor: Prof. Dr.-Ing. Heiko Tapken
# SPDX-FileContributor: Tobias Wamhof
#
# SPDX-License-Identifier: MIT

"""message

Revision ID: afd44e1e43ee
Revises: fe42c67bae2d
Create Date: 2024-07-23 16:46:03.550252

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "afd44e1e43ee"
down_revision = "fe42c67bae2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inference_container_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("git_url", sa.String(), nullable=True),
        sa.Column("git_ref", sa.String(), nullable=True),
        sa.Column("dirname", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inference_container_templates_id"),
        "inference_container_templates",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_inference_container_templates_id"),
        table_name="inference_container_templates",
    )
    op.drop_table("inference_container_templates")
    # ### end Alembic commands ###
