# SPDX-FileCopyrightText: 2024 University of Applied Sciences Osnabrück
# SPDX-FileContributor: Andreas Schliebitz
# SPDX-FileContributor: Henri Graf
# SPDX-FileContributor: Jonas Tüpker
# SPDX-FileContributor: Lukas Hesse
# SPDX-FileContributor: Maik Fruhner
# SPDX-FileContributor: Prof. Dr.-Ing. Heiko Tapken
# SPDX-FileContributor: Tobias Wamhof
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""redo port bindings

Revision ID: cc96a183592c
Revises: 7c29515f8a0b
Create Date: 2022-05-06 08:36:04.311211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cc96a183592c"
down_revision = "7c29515f8a0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "port_bindings",
        sa.Column("host_port", sa.Integer(), nullable=False),
        sa.Column("container_port", sa.Integer(), nullable=False),
        sa.Column(
            "protocol",
            sa.Enum("udp", "tcp", name="portbindingprotocol"),
            nullable=False,
        ),
        sa.Column("container_deployment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["container_deployment_id"],
            ["container_deployments.id"],
        ),
        sa.PrimaryKeyConstraint(
            "host_port", "container_port", "protocol", "container_deployment_id"
        ),
    )
    op.drop_table("port_mappings")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "port_mappings",
        sa.Column("from", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("to", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "protocol",
            postgresql.ENUM("udp", "tcp", name="portmappingprotocol"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "container_deployment_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["container_deployment_id"],
            ["container_deployments.id"],
            name="port_mappings_container_deployment_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "from",
            "to",
            "protocol",
            "container_deployment_id",
            name="port_mappings_pkey",
        ),
    )
    op.drop_table("port_bindings")
    # ### end Alembic commands ###
