# SPDX-FileCopyrightText: 2024 University of Applied Sciences Osnabrück
# SPDX-FileContributor: Andreas Schliebitz
# SPDX-FileContributor: Henri Graf
# SPDX-FileContributor: Jonas Tüpker
# SPDX-FileContributor: Lukas Hesse
# SPDX-FileContributor: Maik Fruhner
# SPDX-FileContributor: Prof. Dr.-Ing. Heiko Tapken
# SPDX-FileContributor: Tobias Wamhof
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Add compressed image size to container

Revision ID: d58e8ff3da3a
Revises: 8277bb769b3b
Create Date: 2022-07-22 09:59:35.335806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d58e8ff3da3a"
down_revision = "8277bb769b3b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "containers", sa.Column("compressed_image_size", sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("containers", "compressed_image_size")
    # ### end Alembic commands ###
