# SPDX-FileCopyrightText: 2024 University of Applied Sciences Osnabrück
# SPDX-FileContributor: Andreas Schliebitz
# SPDX-FileContributor: Henri Graf
# SPDX-FileContributor: Jonas Tüpker
# SPDX-FileContributor: Lukas Hesse
# SPDX-FileContributor: Maik Fruhner
# SPDX-FileContributor: Prof. Dr.-Ing. Heiko Tapken
# SPDX-FileContributor: Tobias Wamhof
#
# SPDX-License-Identifier: MIT

"""Add unique constraint for repository, tag and platform to containers table

Revision ID: f6f8f4c3a2f4
Revises: c2c31d0b2e07
Create Date: 2023-04-24 11:34:41.794059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f6f8f4c3a2f4"
down_revision = "c2c31d0b2e07"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "_repository_tag_platform_uc", "containers", ["repository", "tag", "platform"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_repository_tag_platform_uc", "containers", type_="unique")
    # ### end Alembic commands ###
