# SPDX-FileCopyrightText: 2024 University of Applied Sciences Osnabrück
# SPDX-FileContributor: Andreas Schliebitz
# SPDX-FileContributor: Henri Graf
# SPDX-FileContributor: Jonas Tüpker
# SPDX-FileContributor: Lukas Hesse
# SPDX-FileContributor: Maik Fruhner
# SPDX-FileContributor: Prof. Dr.-Ing. Heiko Tapken
# SPDX-FileContributor: Tobias Wamhof
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Adding new entity type 'TrainContainer'.

Revision ID: f855b83d3f97
Revises: 4aa84b223571
Create Date: 2022-07-11 13:47:09.524955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f855b83d3f97'
down_revision = '4aa84b223571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train_containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('repository', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('architecture', sa.String(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_containers_id'), 'train_containers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_train_containers_id'), table_name='train_containers')
    op.drop_table('train_containers')
    # ### end Alembic commands ###
